use kakoi_net::host_dns::upstreams_from_resolv_conf;

// @kotowari[REQ-145]
#[test]
fn only_the_systemd_resolved_stub_is_followed_through_its_proxy() {
    for text in [
        "nameserver 127.0.0.53\noptions edns0 trust-ad\nsearch .\n",
        "# Generated by systemd-resolved\nnameserver 127.0.0.53\n",
    ] {
        let upstreams = upstreams_from_resolv_conf(text).unwrap();
        assert_eq!(upstreams.len(), 1);
        assert_eq!(upstreams[0].address.to_string(), "127.0.0.54");
        assert_eq!(upstreams[0].port().get(), 53);
        assert!(upstreams[0].tls_name().is_none());
    }
    for text in [
        // A resolver the host uses directly, as WSL writes it.
        "nameserver 10.255.255.254\nsearch example.test\n",
        // The stub and another server: the host would not use the stub alone.
        "nameserver 127.0.0.53\nnameserver 192.0.2.53\n",
        "nameserver ::1\n",
        "search example.test\n",
        "",
    ] {
        let error = upstreams_from_resolv_conf(text).unwrap_err();
        assert!(error.contains("network.dns-upstream"), "{error}");
    }
}
